language: node_js
node_js:
  - "node"
  - "6"
  - "5"

before_install:
- sudo apt-get update
- sudo apt-get install python2.7
- sudo python2.7 $TRAVIS_BUILD_DIR/utils/gitifyhg/setup.py install

after_script: "npm run-script coverall"
